package main

import (
	"crypto/tls"
	"flag"
	"github.com/lucas-clemente/quic-go"
	"io"
	"log"
	"os"
)

func main() {

	keyLogFile := flag.String("keylog", "", "key log file")
	ip := flag.String("ip", "localhost:4242", "IP:Port Address")
	//verbose := flag.Bool("v", false, "verbose (QUIC detailed logs)")
	//priorities := flag.String("prior","1 1 1","Stream priorities")
	scheduler := flag.String("scheduler","wfq","Scheduler type-> abs: absolute priorities, rr: roundrobin, wfq:weighted fair queue")
	flag.Parse()

	prior := []int{2, 8, 12, 7}

	config := &quic.Config{
		StreamPrior:					prior,
		TypePrior:                        *scheduler,
	}

	// QUIC logger

	var keyLog io.Writer
	if len(*keyLogFile) > 0 {
		f, err := os.Create(*keyLogFile)
		if err != nil {
			log.Fatal(err)
		}
		defer f.Close()
		keyLog = f
	}

	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		KeyLogWriter:       keyLog,
		NextProtos:   []string{"quic-echo-example"},
	}

	session, err := quic.DialAddr(*ip,tlsConf, config)
	if err != nil {
		panic(err)
	}

	stream1,err1 := session.OpenStream()
	stream2,err2 := session.OpenStream()
	stream3,err3 := session.OpenStream()
	stream4,err4 := session.OpenStream()
	//defer stream1.Close()
	//defer stream2.Close()
	//defer stream3.Close()
	//defer stream4.Close()

	if err1 != nil || err2 != nil || err3 != nil || err3 != nil{
		print("Error")
		return
	}
	_, err1 = stream1.Write([]byte("jfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsf"))
	_, err2 = stream2.Write([]byte("Que tal: jfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñ ACABO AQUÍ EL 2"))
	_, err3 = stream3.Write([]byte("?"))
	_, err4 = stream4.Write([]byte("empieza el 4: jfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfkñdfmvlkfmklfklgjsñlfjgldsjglskjgklsdfjkjdgldfjñsfjfñlaksjfaklsdjfkldañsjfñakslfjañekfjalkfjcksdncñkasdjhglksjfñkajkldñjfaskldnckñsadfhaszwasxerdcftvygbhunjimko,lfvgbhjnkmvdfkjvfdskvkldfjvsdfjgkjsfdñgljfdñdgñkldlgñjfdlsgfkldjglkfslñgkdslñflklfdgjñslfjglkñdfmvlkfmklfklgjsñ ACABO AQUÍ EL 4"))
	//time.Sleep(60*time.Second)
	if err1 != nil || err2 != nil || err3 != nil || err4 != nil{
		print("Error")
		return
	}


}
